// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJRhCqbiJacawtjzMYFXvI1bw-MAeBfr4',
    appId: '1:600525047863:web:d8404b20147a5671fb17b2',
    messagingSenderId: '600525047863',
    projectId: 'memory-game-2024',
    authDomain: 'memory-game-2024.firebaseapp.com',
    storageBucket: 'memory-game-2024.appspot.com',
    measurementId: 'G-9KF29JTFTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6GRTUpkSaO2pB0mdfg2B7Z3RQSWVcjCQ',
    appId: '1:600525047863:android:ec36a13cd3e2a0f5fb17b2',
    messagingSenderId: '600525047863',
    projectId: 'memory-game-2024',
    storageBucket: 'memory-game-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4CowcHigqSQ-BBAmHWhlV7Dm1KfmlfpQ',
    appId: '1:600525047863:ios:2ddd5389e4c84be0fb17b2',
    messagingSenderId: '600525047863',
    projectId: 'memory-game-2024',
    storageBucket: 'memory-game-2024.appspot.com',
    iosBundleId: 'com.example.memoryGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4CowcHigqSQ-BBAmHWhlV7Dm1KfmlfpQ',
    appId: '1:600525047863:ios:4b677953eadf3977fb17b2',
    messagingSenderId: '600525047863',
    projectId: 'memory-game-2024',
    storageBucket: 'memory-game-2024.appspot.com',
    iosBundleId: 'com.example.memoryGame.RunnerTests',
  );
}
